import React from "react";
import Head from "next/head";
import { createServerSupabaseClient } from "@supabase/auth-helpers-nextjs";
import AppLayout from "@/components/Layouts/AppLayout";
import Link from "next/link";
import { getProfile, Profile } from "@/lib/utils";

export default function index({ user, profile }) {
  return (
    <>
      <Head>
        <title>User Profile</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppLayout>
        <div className="bg-[#616e7c] mt-10 w-full p-12 px-6 py-10 rounded-lg sm:px-10 sm:py-6">
          <div className="flex justify-between space-x-4">
            <h2 className="font-semibold text-4xl text-[#e4e7eb] mb-4">
              Account
            </h2>
            <div className="flex items-center justify-center">
              <Link
                className="py-1 px-4 text-white rounded-sm bg-green-400 hover:bg-green-500"
                href="/"
              >
                Go home
              </Link>
            </div>
          </div>
          <p className="font-medium mb-6 text-[#e4e7eb]">
            Hi {profile.display_name ?? user.email}, you can update your
            profile, email or password from the following options below:
          </p>

          <ul className="divide-y-2 divide-gray-600 w-1/2 md:w-3/12 text-[#e4e7eb]">
            <li className="flex justify-between hover:bg-green-400 hover:text-white hover:font-semibold ">
              <Link className="block w-full  p-3" href="/account/update">
                Update profile
              </Link>
            </li>
            <li className="flex justify-between hover:bg-green-400 hover:text-white hover:font-semibold ">
              <Link className="block w-full p-3" href="/account/update-email">
                Update email
              </Link>
            </li>
            <li className="flex justify-between hover:bg-green-400 hover:text-white hover:font-semibold ">
              <Link
                className="block w-full p-3"
                href="/account/update-password"
              >
                Update password
              </Link>
            </li>
          </ul>
        </div>
      </AppLayout>
    </>
  );
}

export const getServerSideProps = async (ctx) => {
  //create client
  const supabase = createServerSupabaseClient(ctx);
  //get profile and session from utils
  const { profile, session } = await getProfile(supabase);

  return {
    props: {
      initialSession: session,
      user: session?.user,
      profile,
    },
  };
};
